google.maps.__gjsload__('geometry', function(_){var Qia=function(a,b){return Math.abs(_.be(b-a,-180,180))},Ria=function(a,b,c,d,e){if(!d){c=Qia(a.lng(),c)/Qia(a.lng(),b.lng());if(!e)return e=Math.sin(_.Wd(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Wd(b.lat())),_.Xd(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.R(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Wd(a.lat());a=_.Wd(a.lng());d=_.Wd(b.lat());b=_.Wd(b.lng());c=_.Wd(c);return _.be(_.Xd(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},ys={containsLocation:function(a,b){a=_.He(a);var c=_.be(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var l=e.getAt(h),m=0,p=l.getLength();m<p;++m){var q=l.getAt(m),r=l.getAt((m+1)%p),t=_.be(q.lng(),-180,180),v=_.be(r.lng(),-180,180),w=Math.max(t,v);t=Math.min(t,v);(180<w-t?c>=w||c<t:
c<w&&c>=t)&&Ria(q,r,c,d,f)<a.lat()&&(g=!g)}return g||ys.isLocationOnEdge(a,b)}};_.Qa("module$exports$mapsapi$geometry$polyGeometry.PolyGeometry.containsLocation",ys.containsLocation);
ys.isLocationOnEdge=function(a,b,c){a=_.He(a);c=c||1E-9;var d=_.be(a.lng(),-180,180),e=b instanceof _.hj,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var l=g.getAt(h),m=l.getLength(),p=e?m:m-1,q=0;q<p;++q){var r=l.getAt(q),t=l.getAt((q+1)%m),v=_.be(r.lng(),-180,180),w=_.be(t.lng(),-180,180),y=Math.max(v,w),z=Math.min(v,w);if(v=1E-9>=Math.abs(_.be(v-w,-180,180))&&(Math.abs(_.be(v-d,-180,180))<=c||Math.abs(_.be(w-d,-180,
180))<=c)){v=a.lat();w=Math.min(r.lat(),t.lat())-c;var I=Math.max(r.lat(),t.lat())+c;v=v>=w&&v<=I}if(v)return!0;if(180<y-z?d+c>=y||d-c<=z:d+c>=z&&d-c<=y)if(r=Ria(r,t,d,f,b),Math.abs(r-a.lat())<c)return!0}return!1};_.Qa("module$exports$mapsapi$geometry$polyGeometry.PolyGeometry.isLocationOnEdge",ys.isLocationOnEdge);var zs={computeHeading:function(a,b){a=_.He(a);b=_.He(b);var c=_.Ee(a),d=_.Fe(a);a=_.Ee(b);b=_.Fe(b)-d;return _.be(_.Xd(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.Qa("module$exports$mapsapi$geometry$spherical.Spherical.computeHeading",zs.computeHeading);
zs.computeOffset=function(a,b,c,d){a=_.He(a);b/=d||6378137;c=_.Wd(c);var e=_.Ee(a);a=_.Fe(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.De(_.Xd(Math.asin(g)),_.Xd(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.Qa("module$exports$mapsapi$geometry$spherical.Spherical.computeOffset",zs.computeOffset);
zs.computeOffsetOrigin=function(a,b,c,d){a=_.He(a);c=_.Wd(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.Ee(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.Fe(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.De(_.Xd(g),_.Xd(a))};
_.Qa("module$exports$mapsapi$geometry$spherical.Spherical.computeOffsetOrigin",zs.computeOffsetOrigin);
zs.interpolate=function(a,b,c){a=_.He(a);b=_.He(b);var d=_.Ee(a),e=_.Fe(a),f=_.Ee(b),g=_.Fe(b),h=Math.cos(d),k=Math.cos(f);b=zs.ir(a,b);var l=Math.sin(b);if(1E-6>l)return new _.De(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.De(_.Xd(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Xd(Math.atan2(e,b)))};_.Qa("module$exports$mapsapi$geometry$spherical.Spherical.interpolate",zs.interpolate);
zs.ir=function(a,b){var c=_.Ee(a);a=_.Fe(a);var d=_.Ee(b);b=_.Fe(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};zs.computeDistanceBetween=function(a,b,c){a=_.He(a);b=_.He(b);c=c||6378137;return zs.ir(a,b)*c};_.Qa("module$exports$mapsapi$geometry$spherical.Spherical.computeDistanceBetween",zs.computeDistanceBetween);
zs.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.fi&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=zs.computeDistanceBetween(a[d],a[d+1],b);return c};_.Qa("module$exports$mapsapi$geometry$spherical.Spherical.computeLength",zs.computeLength);zs.computeArea=function(a,b){return Math.abs(zs.computeSignedArea(a,b))};_.Qa("module$exports$mapsapi$geometry$spherical.Spherical.computeArea",zs.computeArea);
zs.dt=function(a){var b=As;isFinite(a)||(b[0]=NaN,b[1]=NaN);var c=Math.round(a/90);a-=90*c;if(30===a||-30===a){a=.5*_.u(Math,"sign").call(Math,a);var d=Math.sqrt(.75)}else d=a/180*Math.PI,a=Math.sin(d),d=Math.cos(d);switch(c&3){case 0:b[0]=a;b[1]=d;break;case 1:b[0]=d;b[1]=-a;break;case 2:b[0]=-a;b[1]=-d;break;default:b[0]=-d,b[1]=a}};var As=Array(2);
zs.ms=function(a,b){zs.dt(a.lat());var c=_.A(As),d=c.next().value;c=c.next().value;zs.dt(a.lng());var e=_.A(As);a=e.next().value;e=e.next().value;b[0]=c*e;b[1]=c*a;b[2]=d};zs.Hy=function(a){for(var b=0,c=1;c<a.length;++c)Math.abs(a[c])<Math.abs(a[b])&&(b=c);c=[0,0,0];c[b]=1;a=[a[1]*c[2]-a[2]*c[1],a[2]*c[0]-a[0]*c[2],a[0]*c[1]-a[1]*c[0]];b=_.u(Math,"hypot").apply(Math,_.qa(a));return[a[0]/b,a[1]/b,a[2]/b]};zs.zv=function(a){for(var b=0;3>b;++b)if(0!==a[b]){if(0>a[b])return[-a[0],-a[1],-a[2]];break}return a};
zs.Ns=function(a,b,c){var d=a[0]*b[1]+a[1]*b[0]+a[2]*b[3]-a[3]*b[2],e=a[0]*b[2]-a[1]*b[3]+a[2]*b[0]+a[3]*b[1],f=a[0]*b[3]+a[1]*b[2]-a[2]*b[1]+a[3]*b[0];c[0]=a[0]*b[0]-a[1]*b[1]-a[2]*b[2]-a[3]*b[3];c[1]=d;c[2]=e;c[3]=f};
zs.Ip=function(a,b,c){var d=a[0]-b[0],e=a[1]-b[1],f=a[2]-b[2],g=a[0]+b[0],h=a[1]+b[1],k=a[2]+b[2],l=g*g+h*h+k*k,m=e*k-f*h;f=f*g-d*k;d=d*h-e*g;e=l*l+m*m+f*f+d*d;0!==e?(b=Math.sqrt(e),c[0]=l/b,c[1]=m/b,c[2]=f/b,c[3]=d/b):(l=zs.Hy(zs.zv([a[0]-b[0],a[1]-b[1],a[2]-b[2]])),m=Array(4),zs.Ip(a,l,m),a=Array(4),zs.Ip(l,b,a),zs.Ns(a,m,c))};
zs.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.fi&&(a=a.getArray());a=(0,_.of)(a);if(0===a.length)return 0;var c=Array(4),d=Array(3),e=[1,0,0,0],f=Array(3);zs.ms(a[a.length-1],f);for(var g=0;g<a.length;++g){zs.ms(a[g],d);zs.Ip(f,d,c);zs.Ns(c,e,e);var h=_.A(d);f[0]=h.next().value;f[1]=h.next().value;f[2]=h.next().value}d=_.A(f);a=d.next().value;c=d.next().value;d=d.next().value;h=_.A(e);e=h.next().value;f=h.next().value;g=h.next().value;h=h.next().value;return 2*Math.atan2(a*f+c*g+
d*h,e)*b*b};_.Qa("module$exports$mapsapi$geometry$spherical.Spherical.computeSignedArea",zs.computeSignedArea);zs.jr=function(a,b,c){return zs.computeSignedArea([a,b,c],1)};zs.XA=function(a,b,c){return Math.abs(zs.jr(a,b,c))};zs.gB=function(a,b,c){return _.u(Math,"sign").call(Math,zs.jr(a,b,c))};var Bs={decodePath:function(a){var b=_.Yd(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g;for(g=0;d<b;++g){var h=1,k=0;do{var l=a.charCodeAt(d++)-63-1;h+=l<<k;k+=5}while(31<=l);e+=h&1?~(h>>1):h>>1;h=1;k=0;do l=a.charCodeAt(d++)-63-1,h+=l<<k,k+=5;while(31<=l);f+=h&1?~(h>>1):h>>1;c[g]=new _.De(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.Qa("module$exports$mapsapi$poly$polylineCodec.PolylineCodec.decodePath",Bs.decodePath);
Bs.encodePath=function(a){a instanceof _.fi&&(a=a.getArray());a=(0,_.of)(a);return Bs.Ly(a,function(b){return[Math.round(1E5*b.lat()),Math.round(1E5*b.lng())]})};_.Qa("module$exports$mapsapi$poly$polylineCodec.PolylineCodec.encodePath",Bs.encodePath);Bs.Ly=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.Yd(a);f<g;++f)e=b?b(a[f]):a[f],Bs.Hs(e[0]-d[0],c),Bs.Hs(e[1]-d[1],c),d=e;return c.join("")};Bs.Hs=function(a,b){Bs.My(0>a?~(a<<1):a<<1,b)};
Bs.My=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};var Sia={encoding:Bs,spherical:zs,poly:ys};_.C.google.maps.geometry=Sia;_.Xe("geometry",Sia);});
