google.maps.__gjsload__('geometry', function(_){var Oia=function(a,b){return Math.abs(_.de(b-a,-180,180))},Pia=function(a,b,c,d,e){if(!d){c=Oia(a.lng(),c)/Oia(a.lng(),b.lng());if(!e)return e=Math.sin(_.Yd(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Yd(b.lat())),_.Zd(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.P(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Yd(a.lat());a=_.Yd(a.lng());d=_.Yd(b.lat());b=_.Yd(b.lng());c=_.Yd(c);return _.de(_.Zd(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},ts={containsLocation:function(a,b){a=_.Ie(a);var c=_.de(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var l=e.getAt(h),m=0,p=l.getLength();m<p;++m){var q=l.getAt(m),r=l.getAt((m+1)%p),t=_.de(q.lng(),-180,180),v=_.de(r.lng(),-180,180),w=Math.max(t,v);t=Math.min(t,v);(180<w-t?c>=w||c<t:
c<w&&c>=t)&&Pia(q,r,c,d,f)<a.lat()&&(g=!g)}return g||ts.isLocationOnEdge(a,b)}};_.Ra("module$exports$mapsapi$geometry$polyGeometry.PolyGeometry.containsLocation",ts.containsLocation);
ts.isLocationOnEdge=function(a,b,c){a=_.Ie(a);c=c||1E-9;var d=_.de(a.lng(),-180,180),e=b instanceof _.bj,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var l=g.getAt(h),m=l.getLength(),p=e?m:m-1,q=0;q<p;++q){var r=l.getAt(q),t=l.getAt((q+1)%m),v=_.de(r.lng(),-180,180),w=_.de(t.lng(),-180,180),y=Math.max(v,w),z=Math.min(v,w);if(v=1E-9>=Math.abs(_.de(v-w,-180,180))&&(Math.abs(_.de(v-d,-180,180))<=c||Math.abs(_.de(w-d,-180,
180))<=c)){v=a.lat();w=Math.min(r.lat(),t.lat())-c;var J=Math.max(r.lat(),t.lat())+c;v=v>=w&&v<=J}if(v)return!0;if(180<y-z?d+c>=y||d-c<=z:d+c>=z&&d-c<=y)if(r=Pia(r,t,d,f,b),Math.abs(r-a.lat())<c)return!0}return!1};_.Ra("module$exports$mapsapi$geometry$polyGeometry.PolyGeometry.isLocationOnEdge",ts.isLocationOnEdge);var us={computeHeading:function(a,b){a=_.Ie(a);b=_.Ie(b);var c=_.Fe(a),d=_.Ge(a);a=_.Fe(b);b=_.Ge(b)-d;return _.de(_.Zd(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.Ra("module$exports$mapsapi$geometry$spherical.Spherical.computeHeading",us.computeHeading);
us.computeOffset=function(a,b,c,d){a=_.Ie(a);b/=d||6378137;c=_.Yd(c);var e=_.Fe(a);a=_.Ge(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.Ee(_.Zd(Math.asin(g)),_.Zd(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.Ra("module$exports$mapsapi$geometry$spherical.Spherical.computeOffset",us.computeOffset);
us.computeOffsetOrigin=function(a,b,c,d){a=_.Ie(a);c=_.Yd(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.Fe(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.Ge(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.Ee(_.Zd(g),_.Zd(a))};
_.Ra("module$exports$mapsapi$geometry$spherical.Spherical.computeOffsetOrigin",us.computeOffsetOrigin);
us.interpolate=function(a,b,c){a=_.Ie(a);b=_.Ie(b);var d=_.Fe(a),e=_.Ge(a),f=_.Fe(b),g=_.Ge(b),h=Math.cos(d),k=Math.cos(f);b=us.Fr(a,b);var l=Math.sin(b);if(1E-6>l)return new _.Ee(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.Ee(_.Zd(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Zd(Math.atan2(e,b)))};_.Ra("module$exports$mapsapi$geometry$spherical.Spherical.interpolate",us.interpolate);
us.Fr=function(a,b){var c=_.Fe(a);a=_.Ge(a);var d=_.Fe(b);b=_.Ge(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};us.computeDistanceBetween=function(a,b,c){a=_.Ie(a);b=_.Ie(b);c=c||6378137;return us.Fr(a,b)*c};_.Ra("module$exports$mapsapi$geometry$spherical.Spherical.computeDistanceBetween",us.computeDistanceBetween);
us.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.bi&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=us.computeDistanceBetween(a[d],a[d+1],b);return c};_.Ra("module$exports$mapsapi$geometry$spherical.Spherical.computeLength",us.computeLength);us.computeArea=function(a,b){return Math.abs(us.computeSignedArea(a,b))};_.Ra("module$exports$mapsapi$geometry$spherical.Spherical.computeArea",us.computeArea);
us.At=function(a){var b=vs;if(isFinite(a)){var c=a%360;a=Math.round(c/90);c-=90*a;if(30===c||-30===c){c=.5*_.u(Math,"sign").call(Math,c);var d=Math.sqrt(.75)}else 45===c||-45===c?(c=_.u(Math,"sign").call(Math,c)*Math.SQRT1_2,d=Math.SQRT1_2):(d=c/180*Math.PI,c=Math.sin(d),d=Math.cos(d));switch(a&3){case 0:b[0]=c;b[1]=d;break;case 1:b[0]=d;b[1]=-c;break;case 2:b[0]=-c;b[1]=-d;break;default:b[0]=-d,b[1]=c}}else b[0]=NaN,b[1]=NaN};var vs=Array(2);
us.Gs=function(a,b){us.At(a.lat());var c=_.A(vs),d=c.next().value;c=c.next().value;us.At(a.lng());var e=_.A(vs);a=e.next().value;e=e.next().value;b[0]=c*e;b[1]=c*a;b[2]=d};us.iz=function(a){for(var b=0,c=1;c<a.length;++c)Math.abs(a[c])<Math.abs(a[b])&&(b=c);c=[0,0,0];c[b]=1;a=[a[1]*c[2]-a[2]*c[1],a[2]*c[0]-a[0]*c[2],a[0]*c[1]-a[1]*c[0]];b=_.u(Math,"hypot").apply(Math,_.qa(a));return[a[0]/b,a[1]/b,a[2]/b]};us.Xv=function(a){for(var b=0;3>b;++b)if(0!==a[b]){if(0>a[b])return[-a[0],-a[1],-a[2]];break}return a};
us.it=function(a,b,c){var d=a[0]*b[1]+a[1]*b[0]+a[2]*b[3]-a[3]*b[2],e=a[0]*b[2]-a[1]*b[3]+a[2]*b[0]+a[3]*b[1],f=a[0]*b[3]+a[1]*b[2]-a[2]*b[1]+a[3]*b[0];c[0]=a[0]*b[0]-a[1]*b[1]-a[2]*b[2]-a[3]*b[3];c[1]=d;c[2]=e;c[3]=f};
us.fq=function(a,b,c){var d=a[0]-b[0],e=a[1]-b[1],f=a[2]-b[2],g=a[0]+b[0],h=a[1]+b[1],k=a[2]+b[2],l=g*g+h*h+k*k,m=e*k-f*h;f=f*g-d*k;d=d*h-e*g;e=l*l+m*m+f*f+d*d;0!==e?(b=Math.sqrt(e),c[0]=l/b,c[1]=m/b,c[2]=f/b,c[3]=d/b):(l=us.iz(us.Xv([a[0]-b[0],a[1]-b[1],a[2]-b[2]])),m=Array(4),us.fq(a,l,m),a=Array(4),us.fq(l,b,a),us.it(a,m,c))};
us.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.bi&&(a=a.getArray());a=(0,_.pf)(a);if(0===a.length)return 0;var c=Array(4),d=Array(3),e=[1,0,0,0],f=Array(3);us.Gs(a[a.length-1],f);for(var g=0;g<a.length;++g){us.Gs(a[g],d);us.fq(f,d,c);us.it(c,e,e);var h=_.A(d);f[0]=h.next().value;f[1]=h.next().value;f[2]=h.next().value}d=_.A(f);a=d.next().value;c=d.next().value;d=d.next().value;h=_.A(e);e=h.next().value;f=h.next().value;g=h.next().value;h=h.next().value;return 2*Math.atan2(a*f+c*g+
d*h,e)*b*b};_.Ra("module$exports$mapsapi$geometry$spherical.Spherical.computeSignedArea",us.computeSignedArea);us.Gr=function(a,b,c){return us.computeSignedArea([a,b,c],1)};us.BB=function(a,b,c){return Math.abs(us.Gr(a,b,c))};us.KB=function(a,b,c){return _.u(Math,"sign").call(Math,us.Gr(a,b,c))};var ws={decodePath:function(a){var b=_.$d(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g;for(g=0;d<b;++g){var h=1,k=0;do{var l=a.charCodeAt(d++)-63-1;h+=l<<k;k+=5}while(31<=l);e+=h&1?~(h>>1):h>>1;h=1;k=0;do l=a.charCodeAt(d++)-63-1,h+=l<<k,k+=5;while(31<=l);f+=h&1?~(h>>1):h>>1;c[g]=new _.Ee(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.Ra("module$exports$mapsapi$poly$polylineCodec.PolylineCodec.decodePath",ws.decodePath);
ws.encodePath=function(a){a instanceof _.bi&&(a=a.getArray());a=(0,_.pf)(a);return ws.mz(a,function(b){return[Math.round(1E5*b.lat()),Math.round(1E5*b.lng())]})};_.Ra("module$exports$mapsapi$poly$polylineCodec.PolylineCodec.encodePath",ws.encodePath);ws.mz=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.$d(a);f<g;++f)e=b?b(a[f]):a[f],ws.bt(e[0]-d[0],c),ws.bt(e[1]-d[1],c),d=e;return c.join("")};ws.bt=function(a,b){ws.nz(0>a?~(a<<1):a<<1,b)};
ws.nz=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};var Qia={encoding:ws,spherical:us,poly:ts};_.C.google.maps.geometry=Qia;_.Xe("geometry",Qia);});
